### ISSUE TITLE
LatestFilm component

### ISSUE THREAD

**Issue by luiseulate** [marcbouchenoire/marcbouchenoire.com#42]
Hey @marcbouchenoire I've notice that the letterboxd api response with a 500 status all the time. I don't really now the reason why. Thanks for sharing. Really cool web.

**Comment by marcbouchenoire** [comment]
Hey, thanks for the heads-up!

Looks like Letterboxd URLs might be blocked on Vercel, I'll look more into it soon.

**Comment by marcbouchenoire** [comment]
The issue fixed itself, not sure if on Vercel's or Letterboxd's side but it's fixed.
